### ISSUE TITLE
desitination url is not filled after page selection

### ISSUE THREAD

**Issue by robvis** [do-while/contao-linksplitter#1]
Dear reader,
I'm using Linksplitter and love the intention of the extention.
But I have an issue with selecting pages.
The page url/id is not filled after selection ( I now enter it manually).
Hope you can help me out.

I'm usingContao 4.4.48

Regards,
Rob Vis

**Comment by do-while** [comment]
I have already solved this problem in version 1.1.0, but at that time I only allowed it in Contao 4.6 and higher. Since the problem now also occurs in Contao 4.4, I have now released version 1.1.1 for 4.4 as well.
