### ISSUE TITLE
Issue updating/saving article with Linksplitter module

### ISSUE THREAD

**Issue by robvis** [do-while/contao-linksplitter#2]
Hi Hagen,
I have an issue with linksplitter when saving a linksplitter module in my article in the following situation:
I use linksplitter with "Terminal42 changelanguage", so the destination Url looks like:
{{changelanguage_link_url::137::en}} : this works OK
But I have an issue with references to inserttags: {{changelanguage_link_url::137::{{page::language}}}}
The linksplitter module saves fine.

**The inserttag is translated to "" when recalling and saving in an article.**
The article in BE gives an internal server error with the messager **"" is not a supported language format**
See attachement.

Hope you can solve this issue.
Best Regards, 
Rob Vis

![image](https://user-images.githubusercontent.com/32883690/104449510-fcd5dd00-559e-11eb-89d6-1312fbe3dbe8.png)

**Comment by do-while** [comment]
The problem will be that an InsertTag in the backend cannot determine the language of the target page. As a result, the InsertTag then returns an empty string, which in turn triggers an error in the enclosing InsertTag.
The link splitter resolves the InsertTags via the normal core function replaceInsertTags(), so the error is noticed in the core. However, the cause remains the passing of an invalid InsertTag.

Das Problem wird sein, dass ein InsertTag im Backend die Sprache der Zielseite nicht ermitteln kann. Dadurch gibt der InsertTag dann einen Leerstring zurück, der wiederum in dem umschließenden InsertTag einen Fehler auslöst.
Der Linksplitter löst die InsertTags über die normale Core-Funktion replaceInsertTags() auf, der Fehler wird also im Core bemerkt. Ursache bleibt aber die Übergabe eines ungültigen InsertTags.

**Comment by robvis** [comment]
Hi Hagen,
Vielen Dank fuer Ihre schnellen feedback.
Ich denke, dass ich eine loesung habe durch {{iflng}} und {{ifnlng}} zu nutzen.
**{{changelanguage_link_url::137::{{ifnlng}}en{{iflng}}{{page::language}}}}**
Ist es ueberhaupt auch moeglich andere Bedingungen zu nutzen met Inserttags?
(Gibt es Erweiterungen dafuer?).

Hat dass recht?

Gruesse,
Rob Vis

**Comment by do-while** [comment]
InsertTags können auch als Bedingung verwendet werden.

Welche Erweiterungen soll es geben? Da verstehe ich den Hintergrund der Frage nicht.
